export { default as Home } from './home';
export { default as SignIn } from './signIn';
export { default as SignUp } from './signUp';
export { default as Category } from './category';
export { default as EditProfile } from './editProfile';
export { default as Profile } from './profile';
export { default as SetPassword } from './setPassword';
export { default as Wishlist } from './wishlist';
export { default as ChangePassword } from './changePassword';
export { default as PrivacyPolicy } from './privacyPolicy';
export { default as TermsAndCondition } from './termsAndCondition';
export { default as GiveFeedback } from './giveFeedback';
export { default as PaymentMethod } from './paymentMethod';
export { default as Notification } from './notification';
export { default as OrderHistory } from './order';
export { default as Cart } from './cart';
export {default as ProductDetail} from './productDetail';
export {default as CartDetail} from './cartDetail';
export {default as AddCard} from './addCard';
export {default as ForgetPass} from './forgetPass';
export {default as OTP} from './otp';
export {default as OrderConfirmation} from './orderConfirmation';